In [78]:
import numpy as np

In [79]:
a=np.array([[1,2,3,4,5],[6,7,8,9,0]])
a

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 9, 0]])

In [80]:
a.shape

(2, 5)

In [81]:
a.ndim

2

In [82]:
a.size

10

In [83]:
type(a)

numpy.ndarray

In [84]:
a1=np.ones((2,4),int)
a1

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [85]:
a0=np.zeros((2,4),int)
a0

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

In [86]:
aran=np.arange(0,10)
aran

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [87]:
arand=np.random.randint(54,85,(3,4),int)
arand

array([[84, 84, 79, 66],
       [55, 79, 58, 81],
       [72, 83, 67, 76]])

In [88]:
arand1=np.random.random(10)
arand1

array([0.8052232 , 0.52164715, 0.90864888, 0.31923609, 0.09045935,
       0.30070006, 0.11398436, 0.82868133, 0.04689632, 0.62628715])

In [89]:
arand2=np.random.rand(3,2)
arand2

array([[0.54758616, 0.819287  ],
       [0.19894754, 0.8568503 ],
       [0.35165264, 0.75464769]])

In [90]:
np.random.seed(10)
rands=np.random.randint(0,10,(4,4))
rands

array([[9, 4, 0, 1],
       [9, 0, 1, 8],
       [9, 0, 8, 6],
       [4, 3, 0, 4]])

In [91]:
np.unique(arand)

array([55, 58, 66, 67, 72, 76, 79, 81, 83, 84])

In [92]:
ara=np.random.randint(10,size=(2,3,4,5))
ara

array([[[[6, 8, 1, 8, 4],
         [1, 3, 6, 5, 3],
         [9, 6, 9, 1, 9],
         [4, 2, 6, 7, 8]],

        [[8, 9, 2, 0, 6],
         [7, 8, 1, 7, 1],
         [4, 0, 8, 5, 4],
         [7, 8, 8, 2, 6]],

        [[2, 8, 8, 6, 6],
         [5, 6, 0, 0, 6],
         [9, 1, 8, 9, 1],
         [2, 8, 9, 9, 5]]],


       [[[0, 2, 7, 3, 0],
         [4, 2, 0, 3, 3],
         [1, 2, 5, 9, 0],
         [1, 0, 1, 9, 0]],

        [[9, 2, 1, 1, 0],
         [0, 5, 9, 0, 4],
         [6, 6, 0, 2, 3],
         [3, 2, 6, 0, 5]],

        [[1, 3, 6, 5, 5],
         [1, 8, 0, 5, 9],
         [8, 5, 7, 8, 5],
         [8, 9, 9, 1, 5]]]])

In [93]:
ara[:,1:2,:2,:3]

array([[[[8, 9, 2],
         [7, 8, 1]]],


       [[[9, 2, 1],
         [0, 5, 9]]]])

In [94]:
ara1=np.random.randint(10,size=(5))
ara1

array([9, 1, 4, 7, 7])

In [95]:
ara1+1

array([10,  2,  5,  8,  8])

In [96]:
ara1-1

array([8, 0, 3, 6, 6])

In [97]:
ara1*2

array([18,  2,  8, 14, 14])

In [98]:
ara1/2

array([4.5, 0.5, 2. , 3.5, 3.5])

In [99]:
ara1//2

array([4, 0, 2, 3, 3], dtype=int32)

In [100]:
ara1%3

array([0, 1, 1, 1, 1], dtype=int32)

In [101]:
ara1**2

array([81,  1, 16, 49, 49])

In [102]:
np.sqrt(ara1)

array([3.        , 1.        , 2.        , 2.64575131, 2.64575131])

In [103]:
np.exp(0)

1.0

In [104]:
np.log(1)

0.0

In [105]:
np.mod(ara1,3)

array([0, 1, 1, 1, 1], dtype=int32)

In [106]:
ran=np.random.randint(100,size=(1000))

In [107]:
ran[:10]

array([91,  9,  7, 22, 32,  3,  9, 52, 76, 68])

In [108]:
np.std(ran)

29.117488834032372

In [109]:
np.var(ran)

847.8281559999999

In [110]:
np.sqrt(np.var(ran))

29.117488834032372

In [111]:
a=np.random.randint(1,10,size=(5,5,10))
a

array([[[5, 5, 6, 3, 4, 5, 2, 6, 9, 1],
        [1, 5, 6, 2, 3, 9, 1, 6, 3, 3],
        [5, 7, 3, 1, 3, 1, 8, 3, 6, 6],
        [2, 5, 2, 8, 9, 8, 5, 5, 3, 8],
        [9, 6, 9, 3, 7, 2, 5, 7, 2, 5]],

       [[1, 6, 5, 7, 2, 3, 3, 3, 5, 9],
        [9, 9, 1, 7, 1, 4, 3, 2, 1, 3],
        [4, 1, 2, 4, 1, 2, 1, 4, 4, 4],
        [1, 9, 3, 9, 4, 6, 1, 6, 3, 5],
        [4, 2, 6, 4, 7, 5, 2, 9, 1, 5]],

       [[9, 4, 4, 4, 8, 9, 7, 2, 6, 9],
        [4, 9, 9, 9, 3, 2, 8, 4, 8, 8],
        [3, 8, 5, 2, 1, 8, 4, 8, 4, 8],
        [3, 5, 5, 4, 7, 2, 8, 2, 6, 6],
        [6, 7, 2, 8, 2, 7, 1, 3, 3, 7]],

       [[9, 6, 8, 2, 8, 2, 2, 2, 3, 6],
        [2, 9, 3, 6, 9, 7, 4, 4, 9, 3],
        [1, 8, 4, 4, 1, 5, 3, 4, 7, 7],
        [5, 8, 5, 2, 1, 5, 6, 8, 1, 7],
        [1, 6, 9, 3, 9, 4, 3, 5, 4, 4]],

       [[8, 7, 7, 3, 2, 2, 4, 4, 1, 5],
        [8, 8, 5, 1, 3, 7, 8, 5, 1, 8],
        [6, 4, 9, 7, 1, 4, 6, 1, 5, 6],
        [2, 7, 5, 7, 2, 3, 8, 2, 4, 3],
        [9, 8, 2, 1, 9, 6, 1, 9,

In [112]:
a.reshape(10,5,5)

array([[[5, 5, 6, 3, 4],
        [5, 2, 6, 9, 1],
        [1, 5, 6, 2, 3],
        [9, 1, 6, 3, 3],
        [5, 7, 3, 1, 3]],

       [[1, 8, 3, 6, 6],
        [2, 5, 2, 8, 9],
        [8, 5, 5, 3, 8],
        [9, 6, 9, 3, 7],
        [2, 5, 7, 2, 5]],

       [[1, 6, 5, 7, 2],
        [3, 3, 3, 5, 9],
        [9, 9, 1, 7, 1],
        [4, 3, 2, 1, 3],
        [4, 1, 2, 4, 1]],

       [[2, 1, 4, 4, 4],
        [1, 9, 3, 9, 4],
        [6, 1, 6, 3, 5],
        [4, 2, 6, 4, 7],
        [5, 2, 9, 1, 5]],

       [[9, 4, 4, 4, 8],
        [9, 7, 2, 6, 9],
        [4, 9, 9, 9, 3],
        [2, 8, 4, 8, 8],
        [3, 8, 5, 2, 1]],

       [[8, 4, 8, 4, 8],
        [3, 5, 5, 4, 7],
        [2, 8, 2, 6, 6],
        [6, 7, 2, 8, 2],
        [7, 1, 3, 3, 7]],

       [[9, 6, 8, 2, 8],
        [2, 2, 2, 3, 6],
        [2, 9, 3, 6, 9],
        [7, 4, 4, 9, 3],
        [1, 8, 4, 4, 1]],

       [[5, 3, 4, 7, 7],
        [5, 8, 5, 2, 1],
        [5, 6, 8, 1, 7],
        [1, 6, 9, 3, 9],
        [4,

In [113]:
a.shape

(5, 5, 10)

In [114]:
a.T

array([[[5, 1, 9, 9, 8],
        [1, 9, 4, 2, 8],
        [5, 4, 3, 1, 6],
        [2, 1, 3, 5, 2],
        [9, 4, 6, 1, 9]],

       [[5, 6, 4, 6, 7],
        [5, 9, 9, 9, 8],
        [7, 1, 8, 8, 4],
        [5, 9, 5, 8, 7],
        [6, 2, 7, 6, 8]],

       [[6, 5, 4, 8, 7],
        [6, 1, 9, 3, 5],
        [3, 2, 5, 4, 9],
        [2, 3, 5, 5, 5],
        [9, 6, 2, 9, 2]],

       [[3, 7, 4, 2, 3],
        [2, 7, 9, 6, 1],
        [1, 4, 2, 4, 7],
        [8, 9, 4, 2, 7],
        [3, 4, 8, 3, 1]],

       [[4, 2, 8, 8, 2],
        [3, 1, 3, 9, 3],
        [3, 1, 1, 1, 1],
        [9, 4, 7, 1, 2],
        [7, 7, 2, 9, 9]],

       [[5, 3, 9, 2, 2],
        [9, 4, 2, 7, 7],
        [1, 2, 8, 5, 4],
        [8, 6, 2, 5, 3],
        [2, 5, 7, 4, 6]],

       [[2, 3, 7, 2, 4],
        [1, 3, 8, 4, 8],
        [8, 1, 4, 3, 6],
        [5, 1, 8, 6, 8],
        [5, 2, 1, 3, 1]],

       [[6, 3, 2, 2, 4],
        [6, 2, 4, 4, 5],
        [3, 4, 8, 4, 1],
        [5, 6, 2, 8, 2],
        [7,

In [115]:
a.shape

(5, 5, 10)

In [116]:
a1=np.random.randint(1,10,(3,5))
a1

array([[7, 4, 3, 4, 7],
       [4, 1, 7, 5, 1],
       [1, 1, 9, 1, 6]])

In [117]:
a1.T

array([[7, 4, 1],
       [4, 1, 1],
       [3, 7, 9],
       [4, 5, 1],
       [7, 1, 6]])

In [118]:
np.random.seed(0)
a2=np.random.randint(0,10,(3,3))
a2

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2]])

In [119]:
np.random.seed(1)
a3=np.random.randint(0,10,(3,3))
a3

array([[5, 8, 9],
       [5, 0, 0],
       [1, 7, 6]])

In [120]:
a2*a3

array([[25,  0, 27],
       [15,  0,  0],
       [ 3, 35, 12]])

In [121]:
np.dot(a2,a3)

array([[28, 61, 63],
       [59, 87, 81],
       [42, 38, 39]])

In [122]:
np.random.seed(0)
a4=np.random.randint(0,10,size=(2,2))
a4

array([[5, 0],
       [3, 3]])

In [123]:
np.random.seed(1)
a5=np.random.randint(0,10,size=(2,2))
a5

array([[5, 8],
       [9, 5]])

In [124]:
a4>a5 , a4>=a5 , a4<a5 , a4<=a5 , a4==a5 , a4!=a5

(array([[False, False],
        [False, False]]),
 array([[ True, False],
        [False, False]]),
 array([[False,  True],
        [ True,  True]]),
 array([[ True,  True],
        [ True,  True]]),
 array([[ True, False],
        [False, False]]),
 array([[False,  True],
        [ True,  True]]))

In [138]:
a6=np.random.randint(1,100,size=(3,4))
a6

array([[89, 14, 48, 73],
       [31, 72,  4, 71],
       [22, 50, 58,  4]])

In [139]:
np.sort(a6)

array([[14, 48, 73, 89],
       [ 4, 31, 71, 72],
       [ 4, 22, 50, 58]])

In [140]:
np.argsort(a6)

array([[1, 2, 3, 0],
       [2, 0, 3, 1],
       [3, 0, 1, 2]], dtype=int64)

In [141]:
np.argmin(a6,axis=1)

array([1, 2, 3], dtype=int64)

In [142]:
np.argmax(a6,axis=0)

array([0, 1, 2, 0], dtype=int64)

In [161]:
%%html
<img src="numpy-images/dog-photo.png">

In [157]:
from matplotlib.image import imread
imread("numpy-images/dog-photo.png")

array([[[0.70980394, 0.80784315, 0.88235295, 1.        ],
        [0.72156864, 0.8117647 , 0.8862745 , 1.        ],
        [0.7411765 , 0.8156863 , 0.8862745 , 1.        ],
        ...,
        [0.49803922, 0.6862745 , 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ],
        [0.49411765, 0.68235296, 0.8352941 , 1.        ]],

       [[0.69411767, 0.8039216 , 0.8862745 , 1.        ],
        [0.7019608 , 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49411765, 0.68235296, 0.84313726, 1.        ],
        [0.49411765, 0.68235296, 0.8392157 , 1.        ]],

       [[0.6901961 , 0.8       , 0.88235295, 1.        ],
        [0.69803923, 0.8039216 , 0.88235295, 1.        ],
        [0.7058824 , 0.80784315, 0.88235295, 1.        ],
        ...,
        [0.5019608 , 0.6862745 , 0.84705883, 1.        ],
        [0.49803922, 0.686274

In [163]:
%%html
<img src="numpy-images/car-photo.png">

In [164]:
imread("numpy-images/car-photo.png")

array([[[0.5019608 , 0.50980395, 0.4862745 , 1.        ],
        [0.3372549 , 0.34509805, 0.30588236, 1.        ],
        [0.20392157, 0.21568628, 0.14901961, 1.        ],
        ...,
        [0.64705884, 0.7058824 , 0.54901963, 1.        ],
        [0.59607846, 0.63529414, 0.45882353, 1.        ],
        [0.44705883, 0.47058824, 0.3372549 , 1.        ]],

       [[0.44313726, 0.43529412, 0.40392157, 1.        ],
        [0.3137255 , 0.31764707, 0.27450982, 1.        ],
        [0.2       , 0.21176471, 0.14117648, 1.        ],
        ...,
        [0.5058824 , 0.5372549 , 0.4117647 , 1.        ],
        [0.49803922, 0.52156866, 0.39607844, 1.        ],
        [0.4       , 0.42745098, 0.34117648, 1.        ]],

       [[0.39607844, 0.38039216, 0.34117648, 1.        ],
        [0.31764707, 0.3137255 , 0.27450982, 1.        ],
        [0.28627452, 0.29411766, 0.24705882, 1.        ],
        ...,
        [0.44705883, 0.45882353, 0.32156864, 1.        ],
        [0.45882353, 0.482352

In [165]:
%%html
<img src="numpy-images/panda.png">

In [166]:
imread("numpy-images/panda.png")

array([[[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       [[0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        [0.05490196, 0.10588235, 0.06666667],
        ...,
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765],
        [0.16470589, 0.12941177, 0.09411765]],

       ...,

       [[0.13333334, 0.07450981, 0.05490196],
        [0.12156863, 0.0627451 , 0.04313726],
        [0.10980392, 0