In [6]:
import pandas as pd
import numpy as np

In [11]:
np.random.seed(0)
sales=np.random.randint(20,35,size=(5,3))
sales

array([[32, 25, 20],
       [23, 31, 23],
       [27, 29, 23],
       [25, 22, 24],
       [27, 26, 28]])

In [12]:
nut=pd.DataFrame(sales,index=["Mon" , "Tue" , "Wed" , "Thu" , "Fri"],columns=["Almond Butter" , "Peanut Butter" , "Cashew Butter"])
nut

Almond Butter  Peanut Butter  Cashew Butter
Mon             32             25             20
Tue             23             31             23
Wed             27             29             23
Thu             25             22             24
Fri             27             26             28

In [13]:
price=np.array([10,8,12])
price

array([10,  8, 12])

In [15]:
total=np.dot(nut,price.T)
total

array([760, 754, 778, 714, 814])

In [16]:
nut["Total"]=total.T
nut

Almond Butter  Peanut Butter  Cashew Butter  Total
Mon             32             25             20    760
Tue             23             31             23    754
Wed             27             29             23    778
Thu             25             22             24    714
Fri             27             26             28    814